#example deployment for Load VM
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: load-vm
  namespace: default
  annotations:
    vmoperator.vmware.com/image-supported-check: disable
spec:
  className: my-vm-class-2
  imageName: 10.211.167.166/Load-VM.ova 
  powerState: poweredOn
  networkInterfaces:
  - networkName: "VM Network"
    ethernetCardType: "vmxnet3"

---
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachineClass
metadata:
  name: my-vm-class-2
spec:
  hardware:
    cpus: 16
    memory: 8Gi
