#example deployment for Non-RT VM
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: non-rt
  namespace: default
  annotations:
    vmoperator.vmware.com/image-supported-check: disable
spec:
  className: my-vm-class-1
  imageName: 10.211.167.166/mnt/nfs_share/Non-RealTime-Workload.ova
  powerState: poweredOn
  networkInterfaces:
  - networkName: "VM Network"
    ethernetCardType: "vmxnet3"

---

apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachineClass
metadata:
  name: my-vm-class-1
spec:
  hardware:
    cpus: 4
    memory: 8Gi
