#Example Setup of PTP vSwitch/VMKernel/PG And Enabling PTP
apiVersion: esx.vmware.com/v1alpha1
kind: HostConfiguration
metadata:
  name: ptp-sync
  namespace: esx-system
spec:
  layertype: Incremental
  profile: |
    {
        "profile": {
            "esx": {
                "network_vss": {
                    "switches": [
                        {
                            "name": "PTP-Switch",
                            "policy": {
                                "nic_teaming": {
                                    "policy": "LOADBALANCE_SRCID",
                                    "notify_switches": true,
                                    "rolling_order": false,
                                    "link_criteria_beacon": "IGNORE",
                                    "active_nics": [
                                        "vmnic3"
                                    ],
                                    "standby_nics": []
                                },
                                "security": {
                                    "allow_promiscuous": false,
                                    "mac_changes": false,
                                    "forged_transmits": false
                                },
                                "traffic_shaping": {
                                    "enabled": false
                                }
                            },
                            "bridge": {
                                "link_discovery_protocol": {
                                    "protocol": "CDP",
                                    "operation": "LISTEN"
                                },
                                "nics": [
                                    "vmnic3"
                                ]
                            },
                            "num_ports": 1024,
                            "mtu": 1500,
                            "port_groups": [
                                {
                                    "name": "PTP-PG",
                                    "vlan_id": 0
                                }
                            ]
                        }
                    ]
                },
                "network": {
                    "vmknics": [
                        {
                            "device": "vmk1",
                            "ip": {
                                "dhcp": false,
                                "dhcp_dns": false,
                                "ipv6": {
                                    "dhcp": false,
                                    "auto_configuration_enabled": false,
                                    "dhcp_dns": false
                                },
                                "ipv6_enabled": false
                            },
                            "net_stack_instance_key": "defaultTcpipStack",
                            "port_connection_type": "VSS_PORT_GROUP",
                            "port_group": "PTP-PG",
                            "mac_mode": "AUTO_GENERATED",
                            "mtu": 1500,
                            "enabled": true,
                            "ip_route_default_gateway": "192.168.100.1",
                            "enabled_services": {
                                "precision_time_protocol": true
                            }
                        }
                    ],
                    "net_stacks": [
                        {
                            "key": "defaultTcpipStack",
                            "name": "defaultTcpipStack"
                        }
                    ]
                },     
                "system": {
                    "system_time": {
                        "protocol": "PTP",
                        "enabled": true
                    }
                }
            }
        },
        "host-specific": {
            "66dfd748-cf5c-f819-2029-70f8e7d00dbc": {
                "esx": {
                   "network": {
                       "vmknics": [
                           {
                               "ip": {
                                   "ipv4_address": "192.168.1.4",
                                   "ipv4_subnet_mask": "255.255.255.0"
                               },
                               "device": "vmk1"
                           }
                       ]
                   }
               }
           }
       }
    }
